const data = [
    {
        name: "Alice",
        ImageUrl: "ProfilePhoto.png",
        position: "Alumn 2020",
        year: 2020,
        instagramLink: "https://www.instagram.com/alice",
        linkedinLink: "https://www.linkedin.com/in/alice",
    },
    {
        name: "Bob",
        ImageUrl: "ProfilePhoto.png",
        position: "Alumn 2021",
        year: 2021,
        instagramLink: "https://www.instagram.com/bob",
        linkedinLink: "https://www.linkedin.com/in/bob",
    },
    {
        name: "Alice",
        ImageUrl: "ProfilePhoto.png",
        position: "Alumn 2020",
        year: 2020,
        instagramLink: "https://www.instagram.com/alice",
        linkedinLink: "https://www.linkedin.com/in/alice",
    },
    {
        name: "Bob",
        ImageUrl: "ProfilePhoto.png",
        position: "Alumn 2021",
        year: 2021,
        instagramLink: "https://www.instagram.com/bob",
        linkedinLink: "https://www.linkedin.com/in/bob",
    },
    {
        name: "Alice",
        ImageUrl: "ProfilePhoto.png",
        position: "Alumn 2020",
        year: 2020,
        instagramLink: "https://www.instagram.com/alice",
        linkedinLink: "https://www.linkedin.com/in/alice",
    },
    {
        name: "Bob",
        ImageUrl: "ProfilePhoto.png",
        position: "Alumn 2021",
        year: 2021,
        instagramLink: "https://www.instagram.com/bob",
        linkedinLink: "https://www.linkedin.com/in/bob",
    },
    {
        name: "Alice",
        ImageUrl: "ProfilePhoto.png",
        position: "Alumn 2020",
        year: 2020,
        instagramLink: "https://www.instagram.com/alice",
        linkedinLink: "https://www.linkedin.com/in/alice",
    },
    {
        name: "Bob",
        ImageUrl: "ProfilePhoto.png",
        position: "Alumn 2021",
        year: 2021,
        instagramLink: "https://www.instagram.com/bob",
        linkedinLink: "https://www.linkedin.com/in/bob",
    },
    {
        name: "Alice",
        ImageUrl: "ProfilePhoto.png",
        position: "Alumn 2020",
        year: 2020,
        instagramLink: "https://www.instagram.com/alice",
        linkedinLink: "https://www.linkedin.com/in/alice",
    },
    {
        name: "Bob",
        ImageUrl: "ProfilePhoto.png",
        position: "Alumn 2021",
        year: 2021,
        instagramLink: "https://www.instagram.com/bob",
        linkedinLink: "https://www.linkedin.com/in/bob",
    },
    {
        name: "Alice",
        ImageUrl: "ProfilePhoto.png",
        position: "Alumn 2020",
        year: 2020,
        instagramLink: "https://www.instagram.com/alice",
        linkedinLink: "https://www.linkedin.com/in/alice",
    },
    {
        name: "Bob",
        ImageUrl: "ProfilePhoto.png",
        position: "Alumn 2021",
        year: 2021,
        instagramLink: "https://www.instagram.com/bob",
        linkedinLink: "https://www.linkedin.com/in/bob",
    },
    {
        name: "Alice",
        ImageUrl: "ProfilePhoto.png",
        position: "Alumn 2023",
        year: 2023,
        instagramLink: "https://www.instagram.com/alice",
        linkedinLink: "https://www.linkedin.com/in/alice",
    },
    {
        name: "Bob",
        ImageUrl: "ProfilePhoto.png",
        position: "Alumn 2023",
        year: 2023,
        instagramLink: "https://www.instagram.com/bob",
        linkedinLink: "https://www.linkedin.com/in/bob",
    },
    {
        name: "Alice",
        ImageUrl: "ProfilePhoto.png",
        position: "Alumn 2018",
        year: 2018,
        instagramLink: "https://www.instagram.com/alice",
        linkedinLink: "https://www.linkedin.com/in/alice",
    },
    {
        name: "Bob",
        ImageUrl: "ProfilePhoto.png",
        position: "Alumn 2019",
        year: 2019,
        instagramLink: "https://www.instagram.com/bob",
        linkedinLink: "https://www.linkedin.com/in/bob",
    },
    {
        name: "Alice",
        ImageUrl: "ProfilePhoto.png",
        position: "Alumn 2024",
        year: 2024,
        instagramLink: "https://www.instagram.com/alice",
        linkedinLink: "https://www.linkedin.com/in/alice",
    },
    {
        name: "Bob",
        ImageUrl: "ProfilePhoto.png",
        position: "Alumn 2022",
        year: 2022,
        instagramLink: "https://www.instagram.com/bob",
        linkedinLink: "https://www.linkedin.com/in/bob",
    },

    // Add more alumni with correct year...
];

export default data;
